export RSVDB=cockroach
export TRKDB=atlas
export SLCAL_SQLUSR=mystique 
export SLCAL_SQLPWD=mystique 
export SLCAL_SQLDB=mysrsv 
export SLCAL_MGUSR=mystique 
export SLCAL_MGPWD=mystique 
export SLCAL_MGDB=mystrk
export PGHOST=p.cwwbmz6venfjtnxpg7rzm5fbnq.db.postgresbridge.com
export PGUSER=postgres
export PGPASSWORD=YrFpL3O6sosEbCYI6co4NrXm2te7piREydoIp8C0fwNxA0jmaFteiKMGDb5g20SM
export COCKROACH_USR=mystique
export COCKROACH_PWD=KQDgHkQJMcjLvA4ARaVpXg
export COCKROACH_HOST=free-tier4.aws-us-west-2.cockroachlabs.cloud
export COCKROACH_PORT=26257
export COCKROACH_OPTIONS="--cluster=lanky-quokka-3318&sslmode=require"
export ATLAS_HOST=cluster0.brwd1.mongodb.net
export ATLAS_USERNAME=atlas-db-user-1641355160695861880
export ATLAS_PASSWORD="a1)9=25v"
export ATLAS_DB=mystrk
export GMAPS_KEY=AIzaSyARqfACf-Q-48tihr5CLHnRdrPKPQ2L984
